server:
  port: 8000
  servlet:
    context-path: /ds
spring:
  datasource:
    url: jdbc:mysql://master:3306/stlife_ds?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: cloud
    driver-class-name: com.mysql.cj.jdbc.Driver
